[project]
src = "src"

[networks.contracts.price_feed]
deployer_script = "script/deploy_mocks.py"
abi = "mock_V3_aggregator"


# [networks.pyevm.contracts.price_feed]
# deployer_script = "script/deploy_mocks.py"
[networks.buildBear]
url = "$BUILDBEAR_RPC_URL"
prompt_live = false
save_to_db = false
default_account_name = "buildBear"

[networks.buildBear.contracts.price_feed]
address = "0x694AA1769357215DE4FAC081bf1f309aDC325306"



# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html
